### ISSUE TITLE
[Feature Request] Themed / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [SpiritCroc/Modular-Remote#7]
[https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming)

**Comment by sebastien46** [comment]
@SpiritCroc can I work on this?
if so, I'd also like to refactor the regular / adaptive icon to use the [VectorDrawable](https://developer.android.com/develop/ui/views/graphics/vector-drawable-resources) version of the icon for compatible devices if you're ok with that.
For the icon in general, do I use:
- The version with a back?
- The version with buttons only?

**Comment by SpiritCroc** [comment]
For the monochrome icon, sure, thanks for your interest!
What's the benefit of converting the mipmap icons to VectorDrawable? At least back in the day, mipmap was less computationally expensive for devices (yeah, doesn't matter much for new devices, but do we have downsides?), and [seems to be the recommended way still for the launcher icon](https://developer.android.com/studio/write/create-app-icons)?

Note I stopped using this app a while ago and won't spend much time maintaining it in the future, but while it's not violating Google Play Store regulations (e.g. because of too old SDKs or target API), I'm fine with keeping it up there if there is demand, and accepting contributions that are not too much to review.

For the monochrome icon, in case you haven't seen, the current app icon exists in vector form [here in the repo](https://github.com/SpiritCroc/Modular-Remote/blob/master/icons/ic_launcher.svg), so best to use that as a starting point. The SVG includes the remote-shaped background, but it makes more sense to remove that for themed icons just like in adaptive icons, to simplify it as much as possible, such that the monochrome icon can still be understood.

**Comment by SpiritCroc** [comment]
> > What's the benefit of converting the mipmap icons to VectorDrawable? At least back in the day, mipmap was less computationally expensive for devices (yeah, doesn't matter much for new devices, but do we have downsides?), and [seems to be the recommended way still for the launcher icon](https://developer.android.com/studio/write/create-app-icons)?
> 
>     * Devices that don't support VectorDrawables will just fall back to the baked mipmaps.
>       For example, here are some that I generated from the VectorDrawable:
> 

The lack of disadvantage doesn't automatically make it a benefit, so I don't see this question answered.

> I tried sticking to the old style as closely as possible, while still having it fit adaptive icons (maximum is ~= 46.680x46.680 for round icons), but the old one just doesn't fit very well amongst other icons in general due to it's singular shape.

Please use the same size as the current adaptive icon. If I remember correctly, the factor compared to a normal icon should be either 1.5 or 0.75, depending on what resolution you're working in, + adding appropriate amount of padding.
From another project:
- If the normal icon has canvas size 192x192,
- the canvas size is 216x216 for the adaptive icon
- and while the canvas size is increased, the actual icon is actually scaled down by at least factor 0.75 (I think that was the factor, but better check with the existing adaptive icons in this project)

Apart from the inconsistent size to the previous icon, monochrome icons look good :+1:
